server:
  port: 4000
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: yuanhan_admin
    password: Yuanhan1234
    url: jdbc:mysql://rm-bp14g20lqha9s9fif.mysql.rds.aliyuncs.com:3306/guns_db?autoReconnect=true&characterEncoding=utf-8
  rabbitmq:
    host: 114.55.224.28
    port: 5672
    username: hxb
    password: hxb
      
#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.github.pig.admin.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

qiniu:
  accessKey: cD6GgNSoIAtftkPDHPplHj9ckpzPjOk-D0WdVQrc
  secretKey: 3BQzagZWC0kRlvkNNTne7Ed_pD7qaKqRLuDqh6U7
  bucket: yuanhan
  host: http://ofv9mzx0m.bkt.clouddn.com/
    
logging:
  config: classpath:logback.xml

