server:
  port: 5001

spring:
  rabbitmq:
    host: 114.55.224.28
    port: 5672
    username: hxb
    password: hxb
  boot:
    admin:
      turbine:
        location: pig-monitor
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream

turbine:
    app-config: pig-gateway #收集监控信息的服务名
    combine-host-port: true
    cluster-name-expression: new String('default') #集群名称
